/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CarBrand = IDL.Record({
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'interiorFeatures' : IDL.Vec(IDL.Text),
});
export const PartnerInfo = IDL.Record({
  'name' : IDL.Text,
  'contactEmail' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllCarBrands' : IDL.Func([], [IDL.Vec(CarBrand)], ['query']),
  'getCarBrandByName' : IDL.Func([IDL.Text], [IDL.Opt(CarBrand)], ['query']),
  'getGameFeatures' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPartnerInfo' : IDL.Func([], [PartnerInfo], ['query']),
  'getReleaseDate' : IDL.Func([], [IDL.Nat], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CarBrand = IDL.Record({
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'interiorFeatures' : IDL.Vec(IDL.Text),
  });
  const PartnerInfo = IDL.Record({
    'name' : IDL.Text,
    'contactEmail' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllCarBrands' : IDL.Func([], [IDL.Vec(CarBrand)], ['query']),
    'getCarBrandByName' : IDL.Func([IDL.Text], [IDL.Opt(CarBrand)], ['query']),
    'getGameFeatures' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPartnerInfo' : IDL.Func([], [PartnerInfo], ['query']),
    'getReleaseDate' : IDL.Func([], [IDL.Nat], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };