/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CarBrand {
  'tagline' : string,
  'name' : string,
  'description' : string,
  'interiorFeatures' : Array<string>,
}
export interface PartnerInfo { 'name' : string, 'contactEmail' : string }
export interface Review {
  'id' : bigint,
  'text' : string,
  'author' : string,
  'timestamp' : bigint,
  'rating' : bigint,
}
export interface _SERVICE {
  'getAllCarBrands' : ActorMethod<[], Array<CarBrand>>,
  'getCarBrandByName' : ActorMethod<[string], [] | [CarBrand]>,
  'getGameFeatures' : ActorMethod<[], Array<string>>,
  'getPartnerInfo' : ActorMethod<[], PartnerInfo>,
  'getReleaseDate' : ActorMethod<[], bigint>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'submitReview' : ActorMethod<[string, bigint, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];